# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-10-20 05:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carrera',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('intitucion', models.CharField(max_length=30)),
                ('calificacionTotal', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Valoracion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cursando', models.BooleanField(default=False, verbose_name=b'Cursando actualmente?')),
                ('pros', models.TextField()),
                ('contras', models.TextField()),
                ('recomendacion', models.BooleanField(default=False, verbose_name=b'La recomendarias?')),
                ('fecha_valoracion', models.DateTimeField(verbose_name=b'fecha de valoracion')),
            ],
        ),
        migrations.AddField(
            model_name='carrera',
            name='Valoracion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appcarreras.Valoracion'),
        ),
    ]
