# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-10-20 05:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appcarreras', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='valoracion',
            name='calificacion',
            field=models.CharField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=1, max_length=2),
        ),
    ]
