# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-10-20 14:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appcarreras', '0002_valoracion_calificacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carrera',
            name='Valoracion',
        ),
        migrations.RemoveField(
            model_name='carrera',
            name='intitucion',
        ),
        migrations.AddField(
            model_name='carrera',
            name='institucion',
            field=models.CharField(default=b'Algo', max_length=30),
        ),
        migrations.AddField(
            model_name='valoracion',
            name='carrera',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='appcarreras.Carrera'),
        ),
    ]
