# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-10-20 17:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appcarreras', '0003_auto_20161020_1442'),
    ]

    operations = [
        migrations.AlterField(
            model_name='valoracion',
            name='fecha_valoracion',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
