# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-10-20 18:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appcarreras', '0004_auto_20161020_1744'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carrera',
            name='calificacionTotal',
        ),
        migrations.AlterField(
            model_name='carrera',
            name='institucion',
            field=models.CharField(max_length=30),
        ),
    ]
