# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-10-20 18:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appcarreras', '0005_auto_20161020_1821'),
    ]

    operations = [
        migrations.AlterField(
            model_name='valoracion',
            name='calificacion',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=1),
        ),
    ]
