# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-10-21 02:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appcarreras', '0007_auto_20161020_1856'),
    ]

    operations = [
        migrations.AddField(
            model_name='valoracion',
            name='nombre',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
