# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-10-24 20:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appcarreras', '0008_valoracion_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrera',
            name='nombre',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
