# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-10-31 02:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appcarreras', '0010_auto_20161027_1741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='valoracion',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='appcarreras.Usuario'),
        ),
    ]
