# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-11-01 17:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appcarreras', '0011_auto_20161031_0223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='valoracion',
            name='pros',
            field=models.TextField(max_length=100),
        ),
    ]
