# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-09 04:33
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Carrera',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30, unique=True)),
                ('institucion', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='usuario', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Valoracion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cursando', models.BooleanField(default=False, verbose_name='Cursando actualmente?')),
                ('pros', models.TextField(max_length=100)),
                ('contras', models.TextField()),
                ('recomendacion', models.BooleanField(default=False, verbose_name='La recomendarias?')),
                ('calificacion', models.IntegerField(choices=[(2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], default=2)),
                ('fecha_valoracion', models.DateTimeField(auto_now_add=True)),
                ('carrera', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='carreras.Carrera')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carreras.Usuario')),
            ],
        ),
    ]
