# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-21 18:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carreras', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='valoracion',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carreras.Usuario'),
        ),
    ]
