# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-21 19:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carreras', '0002_auto_20161221_1820'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='valoracion',
            options={'ordering': ('fecha_valoracion',)},
        ),
    ]
