# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-21 19:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carreras', '0003_auto_20161221_1930'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='valoracion',
            options={'ordering': ('-fecha_valoracion',)},
        ),
    ]
