# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-28 03:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carreras', '0004_auto_20161221_1932'),
        ('carreras', '0002_carrera_url'),
    ]

    operations = [
    ]
